"""Semantic link suggester for the SecondaryBrainForClaude vault.

Embeds every note with TF-IDF and computes cosine similarity between all
pairs, then blends in a 4-signal graph relevance model (direct links,
source/folder+tag overlap, Adamic-Adar shared neighbors, type affinity)
mined from nashsu/llm_wiki. Pairs above THRESHOLD that are not already
linked are written to a review note in 00-Inbox/, alongside a knowledge-map
section (clusters, isolated notes, sparse clusters, bridge notes). Nothing
is modified automatically, suggestions only, per BOUNDARIES.md.

Everything runs locally. networkx is used for Louvain clustering when
present; without it a connected-components fallback runs.

Usage (from vault root):
    python3 code/link-suggester/suggest_links.py

Tuning:
    THRESHOLD   minimum blended score to suggest (default 0.18)
    TOP_K       max suggestions per note (default 3)
    GRAPH_W     weight on the normalized graph signal vs TF-IDF (default 0.5)
"""

import os
import re
import sys
from datetime import date

import graph as G  # local module, same folder

THRESHOLD = 0.18
TOP_K = 3
GRAPH_W = 0.5
SKIP_DIRS = {"node_modules"}
SKIP_FOLDERS = {"04-Archives", "99-Meta/templates"}  # read-only / boilerplate

def load_notes(root="."):
    """Collect every markdown note, excluding hidden dirs and archives."""
    notes = {}
    for dp, dn, fn in os.walk(root):
        dn[:] = [d for d in dn if not d.startswith(".") and d not in SKIP_DIRS]
        for f in fn:
            if not f.endswith(".md"):
                continue
            p = os.path.relpath(os.path.join(dp, f), root).replace("\\", "/")
            if any(p.startswith(s) for s in SKIP_FOLDERS):
                continue
            if os.path.basename(p).startswith("link-suggestions-"):
                continue  # the suggester's own output links to everything; skip it
            with open(os.path.join(root, p), encoding="utf-8", errors="ignore") as fh:
                notes[p] = fh.read()
    return notes

def strip_markup(text):
    """Remove code blocks, frontmatter, and link syntax so similarity
    reflects prose content, not shared boilerplate."""
    text = re.sub(r"^---.*?---", "", text, flags=re.S)
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"\[\[([^\]|]+)(\|[^\]]*)?\]\]", r"\1", text)
    return text

def existing_links(notes):
    """Set of (source, target-name) pairs already linked."""
    linked = set()
    for p, t in notes.items():
        me = os.path.splitext(os.path.basename(p))[0].lower()
        for m in re.findall(r"\[\[([^\]|#]+)", t):
            tgt = os.path.splitext(os.path.basename(m.strip()))[0].lower()
            linked.add((me, tgt))
            linked.add((tgt, me))
    return linked

def main():
    notes = load_notes()
    paths = list(notes)
    docs = [strip_markup(notes[p]) for p in paths]

    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity

    vec = TfidfVectorizer(stop_words="english", sublinear_tf=True,
                          max_df=0.8, min_df=2, ngram_range=(1, 2))
    X = vec.fit_transform(docs)
    sim = cosine_similarity(X)

    # Graph signals: build once, normalize the raw signal score to 0..1
    meta, adj, _ = G.build_graph(notes)
    raw = {}
    peak = 0.0
    for i, p in enumerate(paths):
        for j in range(i + 1, len(paths)):
            s = G.signal_score(p, paths[j], meta, adj)
            if s:
                raw[(i, j)] = s
                peak = max(peak, s)
    peak = peak or 1.0

    def blended(i, j):
        g = raw.get((min(i, j), max(i, j)), 0.0) / peak
        return (1 - GRAPH_W) * sim[i, j] + GRAPH_W * g

    linked = existing_links(notes)
    suggestions = {}
    for i, p in enumerate(paths):
        me = os.path.splitext(os.path.basename(p))[0].lower()
        scored = []
        for j, q in enumerate(paths):
            if i == j:
                continue
            other = os.path.splitext(os.path.basename(q))[0].lower()
            b = blended(i, j)
            if (me, other) in linked or b < THRESHOLD:
                continue
            scored.append((b, q))
        scored.sort(reverse=True)
        if scored:
            suggestions[p] = scored[:TOP_K]

    # Knowledge map: clusters, isolated notes, sparse clusters, bridge notes
    comm, cohesion = G.communities(notes, adj)
    isolated, sparse, bridges = G.knowledge_gaps(notes, adj, comm, cohesion)

    out = [f"# Link suggestions {date.today().isoformat()}", "",
           "Generated by code/link-suggester/suggest_links.py (TF-IDF + 4-signal graph).",
           "Review each pair; add a wikilink where the connection is real, "
           "delete the line where it is not. Delete this note when done.", ""]
    for p, scored in sorted(suggestions.items()):
        out.append(f"## {p}")
        for s, q in scored:
            name = os.path.splitext(q)[0]
            out.append(f"- [[{name}]] (score {s:.2f})")
        out.append("")

    out += ["", "# Knowledge map", "",
            "Structural view, not link suggestions. Isolated and sparse areas "
            "are candidates for connect; bridge notes are load-bearing, edit with care.", ""]
    real = {cid: m for cid, m in comm.items() if len(m) >= 2}
    out.append(f"Clusters (>=2 notes): {len(real)}. Isolated notes: {len(isolated)}. "
               f"Bridge notes: {len(bridges)}.")
    out.append("")
    if isolated:
        out.append("## Isolated notes (degree <= 1, candidates for connect)")
        out += [f"- [[{os.path.splitext(p)[0]}]]" for p in isolated[:30]]
        out.append("")
    if sparse:
        out.append("## Sparse clusters (low internal cross-linking)")
        for cid in sparse[:10]:
            members = ", ".join(os.path.basename(m) for m in comm[cid][:6])
            out.append(f"- cohesion {cohesion[cid]}: {members}")
        out.append("")
    if bridges:
        out.append("## Bridge notes (connect 3+ clusters, load-bearing)")
        out += [f"- [[{os.path.splitext(p)[0]}]] ({n} clusters)" for p, n in bridges[:15]]
        out.append("")

    dest = f"00-Inbox/link-suggestions-{date.today().isoformat()}.md"
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"{sum(len(v) for v in suggestions.values())} suggestions across "
          f"{len(suggestions)} notes; {len(real)} clusters, {len(isolated)} isolated, "
          f"{len(bridges)} bridges -> {dest}")

if __name__ == "__main__":
    main()
